#!/bin/bash

PORT=/dev/pff/adc

if ! ${USE_LATCH} ; then
    echo "Latch not installed on this robot. What are you trying to unlock?"
    exit 0
fi

if [[ ! -e $PORT ]]; then
    echo "No device in port: $PORT. Check connections and try again"
    exit 0
fi

ONESHOT=false

pid="$(rosnode list | grep /rosout)"
if [[ -n ${pid} ]]; then
    echo "roscore is already running"
else
    echo "Starting roscore."
    sleep 1
    ONESHOT=true
    roscore &
    sleep 1
fi

topic="$(rostopic list | grep latch_drive)"

if [[ -z $topic ]]; then
    rosrun rosserial_python serial_node.py _port:=$PORT _baud:=115200&
    sleep 4
    rostopic pub -1 /latch_drive std_msgs/Bool true
else
    rostopic pub -1 /r$ROBOT_INDEX/latch_drive std_msgs/Bool true
fi

if $ONESHOT ; then
    k-kill-ros
fi

